services:
  traefik-kop:
    image: jittering/traefik-kop:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@192.168.0.5:6379
      - BIND_IP=192.168.0.7
      - KOP_HOSTNAME=ThinkTank6